name: Task 3 Linter

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo code
        uses: actions/checkout@v2
      - name: Install packages
        run: |
          cd Task3
          cd client
          npm i
          npm run lint
      - name: Lint all files
        run: |
          cd Task3
          cd server
          npm i
          npm run lint